import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({viewport:{width:1500,height:1000}});
await p.goto(process.env.U,{waitUntil:"networkidle"});
await p.waitForTimeout(600);
const fill=async(l,t)=>{const i=p.locator(".field",{hasText:l}).locator("input").first();await i.click();await i.fill(t);};
await fill("Current location","Los Angeles, California");
await fill("Pickup location","Phoenix, Arizona");
await fill("Drop-off location","Dallas, Texas");
await p.locator('input[type=number]').fill("8");
await p.keyboard.press("Escape");
await p.getByRole("button",{name:/Plan trip/}).click();
await p.getByRole("heading",{name:"Daily Log Sheets"}).waitFor({timeout:60000});
await p.waitForTimeout(1500);
const box = await p.locator(".map-intro").boundingBox();
console.log("map-intro text:", (await p.locator(".map-intro").innerText()).slice(0,60));
await p.locator(".card-header").first().screenshot({path:"shot-hdr.png"});
await b.close();
